version: '3'
services:
  dnsserver:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "0.0.0.0:67:67/udp"
    volumes:
      - ./micropython_captive_dhcp_server:/code
    working_dir: "/code"
    #entrypoint: ["tail", "-f", "/dev/null"]
